# docker-compose up --detach --build
version: "3.8"

services:
  api:
    build: "."
    container_name: "biomedicine"
    image: "nchunlplab/biomedicine"
    restart: always
    ports:
      - "44208:8000"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
